---
# ansible-playbook -l <host_group> restart-services.yaml -K
- hosts: all
  tasks:
  - name: Reload Configurations
    shell: systemctl daemon-reload
    become: yes
    become_method: sudo
    tags:
      - canup
      - protostream
      - towercontroller
      - towerstreamsvc
      - daemon-reload
  - name: Restart canup
    service:
      name: canup.service
      state: restarted
    become: yes
    become_method: sudo
    tags:
      - canup
  - name: Restart protostream
    service:
      name: protostream.service
      state: restarted
    become: yes
    become_method: sudo
    tags:
      - protostream
  - name: Restart towercontroller
    service:
      name: towercontroller.service
      state: restarted
    become: yes
    become_method: sudo
    tags:
      - towercontroller
  - name: Restart towerstreamsvc
    service:
      name: towerstreamsvc.service
      state: restarted
    become: yes
    become_method: sudo
    tags:
      - towerstreamsvc
